### ISSUE TITLE
TODO: Participants view

### ISSUE THREAD

**Issue by jsheunis** [leidencid/lcid-metadata-explorer#11]
- [ ] Add intro paragraph
- [ ] Get N data from main excel sheet -  python script
- [ ] Calculate percentages in python?
- [ ] Replace `wave` text with N and percentage
- [ ] Adjust widths and position of legend (overlaps on 13inch screen)
- [ ] Add age ranges to X axis labels on top
