### ISSUE TITLE
TODO: collected view

### ISSUE THREAD

**Issue by jsheunis** [leidencid/lcid-metadata-explorer#12]
- [ ] Add heading
- [ ] Add intro paragraph
- [ ] Add filtering block from table view
- [ ] Replace filter headings with questions
- [ ] Add age ranges to X axis labels on top
- [ ] Put covid wave in the correct position
- [ ] See if hover info can be improved
