### ISSUE TITLE
TODO: table view

### ISSUE THREAD

**Issue by jsheunis** [leidencid/lcid-metadata-explorer#13]
- [ ] Add heading
- [ ] Add intro paragraph
- [ ] Replace filter headings with questions
- [ ] Regain search as you type functionality
- [ ] Add keyword search from cd2
- [ ] Export as csv
- [ ] Column widths https://github.com/leidencid/lcid-metadata-explorer/issues/10
- [ ] Extra carriage return in popup view at sources - fix
- [ ] Add row in popup window: age ranges (if time permits)
