### ISSUE TITLE
TODO: MRI view

### ISSUE THREAD

**Issue by jsheunis** [leidencid/lcid-metadata-explorer#14]
- [ ] Heading and paragraph
- [ ] Data quality: MRI and fMRI
- [ ] fMRI studies results
